<?php

return [
	'start' => 10,
	'order' => [
				'Dealspotr.com',
				'Dontpayfull.com',
				'Dradsdeals.com',
				'Douponsherpa.com',
				'Dealhack.com',
				'Promotioncode.com',
				'Slickdeals.com',
				'GoodSearch.com',
				'Dealoupons.com',
				'Couponforless.com',
				'360couponcodes.com',
				'Couponology.com',
				'Couponlawn.com',
				'Getcouponcodes.com',
				'Coupontwo.com',
				'Couponasion.com',
				'Couponsgood.com',
				'Savedoubler.com',
				'Couponasion.com',
				'Couponsherpa.com',
				'Bradsdeals.com',
				'Copypromocode.com',
				'Anyalles.com',
				'123promocode.com',
				'couponcodeyear.com',
				'nopaymoney.com',
				'couponzguru.com',
				'couponrani.com',
				'coupert.com',
				'dealsea.com',
				'promocodewatch.com',
				'ultimatecoupons.com',
				'chameleonjohn.com',
				'chameleonjohn.com',
				'givingassistant.org',
				'joinhoney.com',
				'theblackfriday.com',
				'dealcatcher.com',
				'grabon.in',
				'rather-be-shopping.com',
				'radins.com',
				'dontpayfull.com'
			]

];
